language: node_js
node_js:
  - 7.6.0
cache:
  directories:
    - node_modules
    - travis_phantomjs
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export PHANTOMJS_VERSION=2.1.1
  - phantomjs --version
script:
  - npm test
  - npm run report-coverage


