language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
env:
  global:
    - CODECOV_TOKEN: 4493d59b-edee-4eab-867f-59f6899bec75
script:
  - npm test
  - npm run report-coverage
  - istanbul cover node_modules/mocha/bin/_mocha
  - cat ./coverage/coverage-final.json | node_modules/codecov.io/bin/codecov.io.js
