language: node_js
node_js:
  - 7.6.0
phantom_js:
  - 2.1.1
cache:
  directories:
    - node_modules
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
  - npm run report-coverage


